### PR TITLE
More robust asyncio stuff, rate limiting, logging 

### PR DESCRIPTION
**Pull request by messa**

### CODE REVIEW

**Comment by hroncok** [comment]
Wow, thanks.

**Comment by messa** [comment]
You can finish the debug logging :) Usually I do something like this:

```
p = ArgumentParser()
p.add_argument('--verbose', '-v', action='store_true')
args = p.parse_args()

logging.basicConfig(level=logging.DEBUG of args.verbose else logging.WARNING)
```

**Comment by hroncok** [comment]
I'm Ok if I comment something in or out for this, but I don't seem to be able to stop the debug logs from urllib3 and bugzilla.

**Comment by hroncok** [comment]
Oh, I got it, thanks.

**Comment by hroncok** [comment]
Still a Ctrl-C is not very nice:

```
$ python monitor_check.py 
5minute failed len=782
astrometry failed len=782
ansible-lint failed len=787
APLpy failed len=780
ansible failed len=780 bz1712531 POST
ansible-review failed len=788
^C2019-06-07 13:41:21,330 asyncio ERROR: SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fabaf3b1898>
transport: <_SelectorSocketTransport fd=63 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib64/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib64/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2019-06-07 13:41:21,332 asyncio ERROR: SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fabb43ad278>
transport: <_SelectorSocketTransport fd=64 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib64/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib64/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2019-06-07 13:41:21,333 asyncio ERROR: SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fabaf377208>
transport: <_SelectorSocketTransport fd=72 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib64/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib64/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2019-06-07 13:41:21,333 asyncio ERROR: SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fabaf35d908>
transport: <_SelectorSocketTransport fd=77 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib64/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib64/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2019-06-07 13:41:21,334 asyncio ERROR: SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fabaf4a1710>
transport: <_SelectorSocketTransport fd=82 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib64/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib64/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2019-06-07 13:41:21,334 asyncio ERROR: SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fabaf42a240>
transport: <_SelectorSocketTransport fd=76 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib64/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib64/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2019-06-07 13:41:21,334 asyncio ERROR: SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fabaf377470>
transport: <_SelectorSocketTransport fd=70 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib64/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib64/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2019-06-07 13:41:21,335 asyncio ERROR: SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fabaf3770b8>
transport: <_SelectorSocketTransport fd=73 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib64/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib64/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2019-06-07 13:41:21,343 asyncio ERROR: SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fabaf39d198>
transport: <_SelectorSocketTransport fd=78 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib64/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib64/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2019-06-07 13:41:21,343 asyncio ERROR: SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fabaf377b70>
transport: <_SelectorSocketTransport fd=66 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib64/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib64/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib64/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
Traceback (most recent call last):
  File "monitor_check.py", line 211, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib64/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
```

**Comment by messa** [comment]
image

**Comment by messa** [comment]
But it looks like it's "just" asyncio logging output, so may be silenced some way?

**Comment by hroncok** [comment]
I've seen this but i only get that if some other exception occurs. Anyway. I have some changes in the async branch, but will not merge this yes, since it would conflict with #2 and that is more critical.

Thanks for the PR, I'll learn a bit more when I resolve conflicts with #2.

**Comment by hroncok** [comment]
Added some commits.

**Comment by messa** [comment]
I've tried if the SSLError could be solved by handling the SIGINT/SIGTERM signals manually (tasks cancelled instead of raising KeyboardInterrupt everywhere), but doesn't seem to help anything

https://github.com/messa/mini-mass-rebuild/commit/b688185d13dcef986d46164f2c21241d5fbd4fef

**Comment by messa** [comment]
```
        try:
            proc = await asyncio.create_subprocess_exec(*cmd,
                                                        stdout=asyncio.subprocess.PIPE)
        except Exception as e:
            raise KojiError(f'Failed to run koji: {e!r}') from None
        stdout, _ = await proc.communicate()
        return b'[BLOCKED]' in stdout
```

I'm not sure if this is 100% safe in all cases - I would like to terminate the subprocess if there are any errors or cancellations after `asyncio.create_subprocess_exec()`. But I've tried

```
        ...
        try:
            stdout, _ = await proc.communicate()
            return b'[BLOCKED]' in stdout
        finally:
            if proc.returncode is None:
                proc.terminate()
                await proc.wait()
```

and it failed with `ProcessLookupError: [Errno 3] No such process`

**Update:** the task is cancelled, so we should clean up all the things, so we should terminate `proc`, _but_ the koji subprocess _also_ receives ctrl-c and manages to quit _before_ we call `proc.terminate()`. That's why it raises `ProcessLookupError` :)

But if koji has already received SIGINT, we should just wait and not send another SIGTERM. Therefore we should send SIGTERM to koji (by `process.terminate()`) only when we haven't received SIGINT (because if we received SIGINT, koji also probably has received SIGINT). It gets complicated pretty quickly :) (Actually I have exactly this code in our process manager library.)

**Comment by messa** [comment]
> Wow, thanks.

I have long-running processes with asyncio, aiohttp, subprocesses :) and other code in production 💸 so I just need to know about every quirk and dark corner of asyncio 😎

**Comment by messa** [comment]
BTW. don't forget that Ctrl-C is sent to all processes in a process group - that includes the `koji` subprocess, so you can observe koji tracebacks intermixed with `monitor_checks.py` tracebacks :)

```
Traceback (most recent call last):
  File "/usr/bin/koji", line 40, in <module>
    import koji
...
Traceback (most recent call last):
  File "monitor_check.py", line 226, in <module>
    asyncio.run(main())
...
```

**Comment by hroncok** [comment]
Merged via #3

**Pull request closed without merging**
